# Generated by Django 4.0.2 on 2022-03-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='country',
        ),
    ]
