# Generated by Django 4.0.4 on 2022-05-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
