# Generated by Django 4.0.4 on 2022-05-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Products',
        ),
        migrations.AddField(
            model_name='cart',
            name='Products',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
