# Generated by Django 4.0.4 on 2022-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_options_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Products',
        ),
        migrations.AddField(
            model_name='cart',
            name='Products',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
