# Generated by Django 4.0.4 on 2022-05-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_cart_options_cart_checked_out_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Products',
        ),
        migrations.AlterField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart'),
        ),
    ]
