# Generated by Django 4.0.4 on 2022-05-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_favourites_products_favourites_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='products',
        ),
        migrations.AddField(
            model_name='favourites',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
