# Generated by Django 4.0.4 on 2022-05-29 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_remove_favourites_products_favourites_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
