# Generated by Django 4.0.4 on 2022-05-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_favourites_user_favourites_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
