# Generated by Django 4.0.4 on 2022-05-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_favourites_products_remove_favourites_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.AddField(
            model_name='favourite',
            name='favourites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.favourites'),
        ),
    ]
