# Generated by Django 4.0.4 on 2022-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_favourite_favourites_favourites_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favourites',
        ),
        migrations.AddField(
            model_name='favourites',
            name='favourites',
            field=models.ManyToManyField(to='store.favourite'),
        ),
    ]
