# Generated by Django 4.0.4 on 2022-05-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_favourite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favourites',
        ),
        migrations.AddField(
            model_name='item',
            name='favourites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.favourites'),
            preserve_default=False,
        ),
    ]
