# Generated by Django 4.0.2 on 2022-03-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.FloatField(help_text='duration of the quiz in minutes'),
        ),
    ]
