# Generated by Django 4.0.2 on 2022-04-05 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0002_answer_question_question_quiz_quiz_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
