# Generated by Django 4.0.2 on 2022-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_alter_quiz_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.FloatField(help_text='duration of the quiz in minutes'),
        ),
    ]
