# Generated by Django 4.0.2 on 2022-04-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quiztaker_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztaker',
            name='game_opponent',
        ),
    ]
