# Generated by Django 4.0.2 on 2022-03-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_alter_quiz_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.FloatField(default='0', help_text='duration of the quiz in minutes'),
        ),
    ]
