# Generated by Django 4.0.2 on 2022-03-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_alter_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='quizimages/'),
        ),
    ]
