# Generated by Django 4.0.2 on 2022-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0006_quiztaker_game_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
