# Generated by Django 4.0.2 on 2022-04-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_alter_quiztaker_date_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='room_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
