# Generated by Django 4.0.2 on 2022-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_alter_quiztaker_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='connected_users',
            field=models.IntegerField(default=0),
        ),
    ]
